//
// Created by sennerosaer on 7/28/19.
//

#ifndef ROADFIGHTER_OBSERVERBACKGROUNDEND_H
#define ROADFIGHTER_OBSERVERBACKGROUNDEND_H

class ObserverBackgroundEnd
{
};

#endif // ROADFIGHTER_OBSERVERBACKGROUNDEND_H
